# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d31be475b32a356c4c8621b65dfa549982e2a720761a54057d4fcbe34a8df3b52c7ea1ea6efaa657a7f125062b65c5259d52d44677764c88e047baf0dd690a0c

test:
  secret_key_base: 785f79fea73d175290a37f31cccb479567e446da096af5f3ada049525dd9c0142db573e08ec4ce00f7ecb4e0fad0455f17bc2454743103f5e2b1929ab22bae58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
